//
// Generated file, do not edit! Created by opp_msgtool 6.0 from IIUC_DWIP_ELITE.msg.
//

#ifndef __IIUC_DWIP_ELITE_M_H
#define __IIUC_DWIP_ELITE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IIUC_DWIP_ELITE;
class IIUC_DWIP_ELITEDataPacket;
/**
 * Enum generated from <tt>IIUC_DWIP_ELITE.msg:12</tt> by opp_msgtool.
 * <pre>
 * enum IIUC_DWIP_ELITEType
 * {
 *     IIUC_CONN_REQ = 0;
 *     IIUC_CONN_ACK = 1;
 *     IIUC_DISC_REQ = 2;
 *     IIUC_DISC_ACK = 3;
 *     IIUC_DATA = 4;
 * }
 * </pre>
 */
enum IIUC_DWIP_ELITEType {
    IIUC_CONN_REQ = 0,
    IIUC_CONN_ACK = 1,
    IIUC_DISC_REQ = 2,
    IIUC_DISC_ACK = 3,
    IIUC_DATA = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IIUC_DWIP_ELITEType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IIUC_DWIP_ELITEType& e) { int n; b->unpack(n); e = static_cast<IIUC_DWIP_ELITEType>(n); }

/**
 * Class generated from <tt>IIUC_DWIP_ELITE.msg:21</tt> by opp_msgtool.
 * <pre>
 * packet IIUC_DWIP_ELITE
 * {
 *     int srcAddress;
 *     int destAddress;
 *     int serverProcId;
 * }
 * </pre>
 */
class IIUC_DWIP_ELITE : public ::omnetpp::cPacket
{
  protected:
    int srcAddress = 0;
    int destAddress = 0;
    int serverProcId = 0;

  private:
    void copy(const IIUC_DWIP_ELITE& other);

  protected:
    bool operator==(const IIUC_DWIP_ELITE&) = delete;

  public:
    IIUC_DWIP_ELITE(const char *name=nullptr, short kind=0);
    IIUC_DWIP_ELITE(const IIUC_DWIP_ELITE& other);
    virtual ~IIUC_DWIP_ELITE();
    IIUC_DWIP_ELITE& operator=(const IIUC_DWIP_ELITE& other);
    virtual IIUC_DWIP_ELITE *dup() const override {return new IIUC_DWIP_ELITE(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress);

    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress);

    virtual int getServerProcId() const;
    virtual void setServerProcId(int serverProcId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IIUC_DWIP_ELITE& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IIUC_DWIP_ELITE& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>IIUC_DWIP_ELITE.msg:28</tt> by opp_msgtool.
 * <pre>
 * packet IIUC_DWIP_ELITEDataPacket extends IIUC_DWIP_ELITE
 * {
 *     string payload;
 * }
 * </pre>
 */
class IIUC_DWIP_ELITEDataPacket : public ::IIUC_DWIP_ELITE
{
  protected:
    omnetpp::opp_string payload;

  private:
    void copy(const IIUC_DWIP_ELITEDataPacket& other);

  protected:
    bool operator==(const IIUC_DWIP_ELITEDataPacket&) = delete;

  public:
    IIUC_DWIP_ELITEDataPacket(const char *name=nullptr, short kind=0);
    IIUC_DWIP_ELITEDataPacket(const IIUC_DWIP_ELITEDataPacket& other);
    virtual ~IIUC_DWIP_ELITEDataPacket();
    IIUC_DWIP_ELITEDataPacket& operator=(const IIUC_DWIP_ELITEDataPacket& other);
    virtual IIUC_DWIP_ELITEDataPacket *dup() const override {return new IIUC_DWIP_ELITEDataPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IIUC_DWIP_ELITEDataPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IIUC_DWIP_ELITEDataPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IIUC_DWIP_ELITE *fromAnyPtr(any_ptr ptr) { return check_and_cast<IIUC_DWIP_ELITE*>(ptr.get<cObject>()); }
template<> inline IIUC_DWIP_ELITEDataPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<IIUC_DWIP_ELITEDataPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __IIUC_DWIP_ELITE_M_H

